FROM mysql

ENV MYSQL_ROOT_PASSWORD video
ENV MYSQL_DATABASE video
ENV MYSQL_USER video
ENV MYSQL_PASSWORD video

RUN /etc/init.d/mysql start && \
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "create database video" && \
mysql -u root -p${MYSQL_ROOT_PASSWORD} video -e "create table [if not exists] videos (ID int not null auto_increment, name varchar(255) not null, path varchar(255) not null, primary key (id));"
